Added module and problem schema for review
university-cs-demo/edugator-staff-backend pull request #9
Opened 2021-09-06 20:11 UTC by dhruv2000

Please let me know what you guys think in regards to this commit. I will look into JOI validation soon. Also, when would you like me to complete this by? I think we said the next meeting, but is that referring to the one next week with aman, or are we doing that this week?

2021-09-06 22:45 UTC, HamishPierpont reviewed
.

2021-09-06 22:47 UTC, HamishPierpont requested changes
Looks solid! A few suggestions:
- `src/models/module.ts`:
  - Remove the comment on line 1
  - Change `Problem` to `problem` on line 13
  - `ObjectId` is actually a [type in MongoDB and mongoose](https://mongoosejs.com/docs/schematypes.html#objectids), so I think you can simplify the problem array to look like this:
  ```javascript
  problem: [mongoose.ObjectId]
  ```
  - Add a newline at the end of the file because GitHub says so
- `src/models/problem.ts`
  - Remove the comment on line 1
  - For `fileExtension`, I don't think `Enumerator` is a [permitted mongoose type](https://mongoosejs.com/docs/schematypes.html). I think we should change the type to `String` and add, next to `type` and `required`, this field:
  ```javascript
  enum: [".java", ".cpp", ".h", ] //I don't know what else could go in here? Maybe ".cxx"?
  ```
  - For `visibility`, I'd replace the min-max validation with `enum: [0, 1, 2]` to avoid any non-integer visibilities from ending up in the DB. This probably would never be an issue, but we might as well have the strictest validation possible.
  - Add a newline at the end of the file because GitHub says so

2021-09-07 18:20 UTC, dhruv2000 commented
I just made some of those changes. Requesting approval again

2021-09-07 18:22 UTC, HamishPierpont approved these changes
Looks great!

2021-09-07 18:38 UTC, marcgabe15 approved these changes

2021-09-07 18:38 UTC, marcgabe15 commented on src/models/problem.ts
> +            /*templatePackage: {
Will clarify with professor today

2021-09-07 18:59 UTC, merged